apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/ecommerce-backend:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 4500
          env:
            - name: MONGODB_URI
              value: mongodb://admin:7325APM@mongo:27017/ecommerce?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 4500        # Service port
      targetPort: 4500 # Container port
